name: .NET 9 Build and Deploy

on:
  push:
    branches: [ "master" ]

env:
  DOTNET_VERSION: '9.0.100' 
  PACKAGE_PATH: './publish'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore & Build
      run: |
        dotnet restore
        dotnet build -c Release --no-restore

    - name: Install EF Core CLI
      run: dotnet tool install --global dotnet-ef

    - name: Apply Database Migrations
      run: dotnet ef database update --project CollegeApp.Server/CollegeApp.Server.csproj
      env:
        ConnectionStrings__DefaultConnection: '${{ secrets.DB_CONNECTION_STRING }}'

    - name: Publish App
      run: dotnet publish -c Release -o ${{ env.PACKAGE_PATH }}


    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'newapp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.PACKAGE_PATH }}